// Code generated by MockGen. DO NOT EDIT.
// Source: ../interface/data_interface.go

// Package mock is a generated GoMock package.
package mock

import (
	io "io"
	reflect "reflect"

	entity "github.com/AnnV0lokitina/diplom1/cmd/gophkeeper/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockRepoData is a mock of RepoData interface.
type MockRepoData struct {
	ctrl     *gomock.Controller
	recorder *MockRepoDataMockRecorder
}

// MockRepoDataMockRecorder is the mock recorder for MockRepoData.
type MockRepoDataMockRecorder struct {
	mock *MockRepoData
}

// NewMockRepoData creates a new mock instance.
func NewMockRepoData(ctrl *gomock.Controller) *MockRepoData {
	mock := &MockRepoData{ctrl: ctrl}
	mock.recorder = &MockRepoDataMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoData) EXPECT() *MockRepoDataMockRecorder {
	return m.recorder
}

// AddBankCard mocks base method.
func (m *MockRepoData) AddBankCard(card entity.BankCard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBankCard", card)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBankCard indicates an expected call of AddBankCard.
func (mr *MockRepoDataMockRecorder) AddBankCard(card interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBankCard", reflect.TypeOf((*MockRepoData)(nil).AddBankCard), card)
}

// AddBinaryFile mocks base method.
func (m *MockRepoData) AddBinaryFile(file entity.File, reader io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBinaryFile", file, reader)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBinaryFile indicates an expected call of AddBinaryFile.
func (mr *MockRepoDataMockRecorder) AddBinaryFile(file, reader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBinaryFile", reflect.TypeOf((*MockRepoData)(nil).AddBinaryFile), file, reader)
}

// AddCredentials mocks base method.
func (m *MockRepoData) AddCredentials(cred entity.Credentials) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCredentials", cred)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCredentials indicates an expected call of AddCredentials.
func (mr *MockRepoDataMockRecorder) AddCredentials(cred interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCredentials", reflect.TypeOf((*MockRepoData)(nil).AddCredentials), cred)
}

// AddTextFile mocks base method.
func (m *MockRepoData) AddTextFile(file entity.File, reader io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTextFile", file, reader)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTextFile indicates an expected call of AddTextFile.
func (mr *MockRepoDataMockRecorder) AddTextFile(file, reader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTextFile", reflect.TypeOf((*MockRepoData)(nil).AddTextFile), file, reader)
}

// CreateZIP mocks base method.
func (m *MockRepoData) CreateZIP() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateZIP")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateZIP indicates an expected call of CreateZIP.
func (mr *MockRepoDataMockRecorder) CreateZIP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateZIP", reflect.TypeOf((*MockRepoData)(nil).CreateZIP))
}

// GetBankCardByNumber mocks base method.
func (m *MockRepoData) GetBankCardByNumber(number string) *entity.BankCard {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBankCardByNumber", number)
	ret0, _ := ret[0].(*entity.BankCard)
	return ret0
}

// GetBankCardByNumber indicates an expected call of GetBankCardByNumber.
func (mr *MockRepoDataMockRecorder) GetBankCardByNumber(number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBankCardByNumber", reflect.TypeOf((*MockRepoData)(nil).GetBankCardByNumber), number)
}

// GetBankCardList mocks base method.
func (m *MockRepoData) GetBankCardList() []entity.BankCard {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBankCardList")
	ret0, _ := ret[0].([]entity.BankCard)
	return ret0
}

// GetBankCardList indicates an expected call of GetBankCardList.
func (mr *MockRepoDataMockRecorder) GetBankCardList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBankCardList", reflect.TypeOf((*MockRepoData)(nil).GetBankCardList))
}

// GetBinaryFileByName mocks base method.
func (m *MockRepoData) GetBinaryFileByName(name string) (*entity.File, io.Reader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBinaryFileByName", name)
	ret0, _ := ret[0].(*entity.File)
	ret1, _ := ret[1].(io.Reader)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBinaryFileByName indicates an expected call of GetBinaryFileByName.
func (mr *MockRepoDataMockRecorder) GetBinaryFileByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBinaryFileByName", reflect.TypeOf((*MockRepoData)(nil).GetBinaryFileByName), name)
}

// GetBinaryFileList mocks base method.
func (m *MockRepoData) GetBinaryFileList() []entity.File {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBinaryFileList")
	ret0, _ := ret[0].([]entity.File)
	return ret0
}

// GetBinaryFileList indicates an expected call of GetBinaryFileList.
func (mr *MockRepoDataMockRecorder) GetBinaryFileList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBinaryFileList", reflect.TypeOf((*MockRepoData)(nil).GetBinaryFileList))
}

// GetCredentialsByLogin mocks base method.
func (m *MockRepoData) GetCredentialsByLogin(login string) *entity.Credentials {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentialsByLogin", login)
	ret0, _ := ret[0].(*entity.Credentials)
	return ret0
}

// GetCredentialsByLogin indicates an expected call of GetCredentialsByLogin.
func (mr *MockRepoDataMockRecorder) GetCredentialsByLogin(login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentialsByLogin", reflect.TypeOf((*MockRepoData)(nil).GetCredentialsByLogin), login)
}

// GetCredentialsList mocks base method.
func (m *MockRepoData) GetCredentialsList() []entity.Credentials {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentialsList")
	ret0, _ := ret[0].([]entity.Credentials)
	return ret0
}

// GetCredentialsList indicates an expected call of GetCredentialsList.
func (mr *MockRepoDataMockRecorder) GetCredentialsList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentialsList", reflect.TypeOf((*MockRepoData)(nil).GetCredentialsList))
}

// GetInfo mocks base method.
func (m *MockRepoData) GetInfo() (*entity.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfo")
	ret0, _ := ret[0].(*entity.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInfo indicates an expected call of GetInfo.
func (mr *MockRepoDataMockRecorder) GetInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfo", reflect.TypeOf((*MockRepoData)(nil).GetInfo))
}

// GetTextFileByName mocks base method.
func (m *MockRepoData) GetTextFileByName(name string) (*entity.File, io.Reader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTextFileByName", name)
	ret0, _ := ret[0].(*entity.File)
	ret1, _ := ret[1].(io.Reader)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTextFileByName indicates an expected call of GetTextFileByName.
func (mr *MockRepoDataMockRecorder) GetTextFileByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTextFileByName", reflect.TypeOf((*MockRepoData)(nil).GetTextFileByName), name)
}

// GetTextFileList mocks base method.
func (m *MockRepoData) GetTextFileList() []entity.File {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTextFileList")
	ret0, _ := ret[0].([]entity.File)
	return ret0
}

// GetTextFileList indicates an expected call of GetTextFileList.
func (mr *MockRepoDataMockRecorder) GetTextFileList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTextFileList", reflect.TypeOf((*MockRepoData)(nil).GetTextFileList))
}

// ReadFileByChunks mocks base method.
func (m *MockRepoData) ReadFileByChunks(w io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFileByChunks", w)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReadFileByChunks indicates an expected call of ReadFileByChunks.
func (mr *MockRepoDataMockRecorder) ReadFileByChunks(w interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFileByChunks", reflect.TypeOf((*MockRepoData)(nil).ReadFileByChunks), w)
}

// RemoveBankCardByNumber mocks base method.
func (m *MockRepoData) RemoveBankCardByNumber(number string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveBankCardByNumber", number)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveBankCardByNumber indicates an expected call of RemoveBankCardByNumber.
func (mr *MockRepoDataMockRecorder) RemoveBankCardByNumber(number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveBankCardByNumber", reflect.TypeOf((*MockRepoData)(nil).RemoveBankCardByNumber), number)
}

// RemoveBinaryFileByName mocks base method.
func (m *MockRepoData) RemoveBinaryFileByName(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveBinaryFileByName", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveBinaryFileByName indicates an expected call of RemoveBinaryFileByName.
func (mr *MockRepoDataMockRecorder) RemoveBinaryFileByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveBinaryFileByName", reflect.TypeOf((*MockRepoData)(nil).RemoveBinaryFileByName), name)
}

// RemoveCredentialsByLogin mocks base method.
func (m *MockRepoData) RemoveCredentialsByLogin(login string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCredentialsByLogin", login)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCredentialsByLogin indicates an expected call of RemoveCredentialsByLogin.
func (mr *MockRepoDataMockRecorder) RemoveCredentialsByLogin(login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCredentialsByLogin", reflect.TypeOf((*MockRepoData)(nil).RemoveCredentialsByLogin), login)
}

// RemoveTextFileByName mocks base method.
func (m *MockRepoData) RemoveTextFileByName(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTextFileByName", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTextFileByName indicates an expected call of RemoveTextFileByName.
func (mr *MockRepoDataMockRecorder) RemoveTextFileByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTextFileByName", reflect.TypeOf((*MockRepoData)(nil).RemoveTextFileByName), name)
}

// UnpackZIP mocks base method.
func (m *MockRepoData) UnpackZIP() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpackZIP")
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpackZIP indicates an expected call of UnpackZIP.
func (mr *MockRepoDataMockRecorder) UnpackZIP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpackZIP", reflect.TypeOf((*MockRepoData)(nil).UnpackZIP))
}

// WriteFileByChunks mocks base method.
func (m *MockRepoData) WriteFileByChunks(reader io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFileByChunks", reader)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFileByChunks indicates an expected call of WriteFileByChunks.
func (mr *MockRepoDataMockRecorder) WriteFileByChunks(reader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFileByChunks", reflect.TypeOf((*MockRepoData)(nil).WriteFileByChunks), reader)
}
