// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/handler.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SecureStorageClient is the client API for SecureStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecureStorageClient interface {
	Register(ctx context.Context, in *UserRegRequest, opts ...grpc.CallOption) (*UserRegResponse, error)
	Login(ctx context.Context, in *UserRegRequest, opts ...grpc.CallOption) (*UserRegResponse, error)
	RestoreFile(ctx context.Context, in *RestoreFileRequest, opts ...grpc.CallOption) (SecureStorage_RestoreFileClient, error)
	StoreFile(ctx context.Context, opts ...grpc.CallOption) (SecureStorage_StoreFileClient, error)
}

type secureStorageClient struct {
	cc grpc.ClientConnInterface
}

func NewSecureStorageClient(cc grpc.ClientConnInterface) SecureStorageClient {
	return &secureStorageClient{cc}
}

func (c *secureStorageClient) Register(ctx context.Context, in *UserRegRequest, opts ...grpc.CallOption) (*UserRegResponse, error) {
	out := new(UserRegResponse)
	err := c.cc.Invoke(ctx, "/proto.SecureStorage/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secureStorageClient) Login(ctx context.Context, in *UserRegRequest, opts ...grpc.CallOption) (*UserRegResponse, error) {
	out := new(UserRegResponse)
	err := c.cc.Invoke(ctx, "/proto.SecureStorage/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secureStorageClient) RestoreFile(ctx context.Context, in *RestoreFileRequest, opts ...grpc.CallOption) (SecureStorage_RestoreFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &SecureStorage_ServiceDesc.Streams[0], "/proto.SecureStorage/RestoreFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &secureStorageRestoreFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SecureStorage_RestoreFileClient interface {
	Recv() (*RestoreFileResponse, error)
	grpc.ClientStream
}

type secureStorageRestoreFileClient struct {
	grpc.ClientStream
}

func (x *secureStorageRestoreFileClient) Recv() (*RestoreFileResponse, error) {
	m := new(RestoreFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *secureStorageClient) StoreFile(ctx context.Context, opts ...grpc.CallOption) (SecureStorage_StoreFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &SecureStorage_ServiceDesc.Streams[1], "/proto.SecureStorage/StoreFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &secureStorageStoreFileClient{stream}
	return x, nil
}

type SecureStorage_StoreFileClient interface {
	Send(*StoreFileRequest) error
	CloseAndRecv() (*StoreFileResponse, error)
	grpc.ClientStream
}

type secureStorageStoreFileClient struct {
	grpc.ClientStream
}

func (x *secureStorageStoreFileClient) Send(m *StoreFileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *secureStorageStoreFileClient) CloseAndRecv() (*StoreFileResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StoreFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SecureStorageServer is the server API for SecureStorage service.
// All implementations must embed UnimplementedSecureStorageServer
// for forward compatibility
type SecureStorageServer interface {
	Register(context.Context, *UserRegRequest) (*UserRegResponse, error)
	Login(context.Context, *UserRegRequest) (*UserRegResponse, error)
	RestoreFile(*RestoreFileRequest, SecureStorage_RestoreFileServer) error
	StoreFile(SecureStorage_StoreFileServer) error
	mustEmbedUnimplementedSecureStorageServer()
}

// UnimplementedSecureStorageServer must be embedded to have forward compatible implementations.
type UnimplementedSecureStorageServer struct {
}

func (UnimplementedSecureStorageServer) Register(context.Context, *UserRegRequest) (*UserRegResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedSecureStorageServer) Login(context.Context, *UserRegRequest) (*UserRegResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedSecureStorageServer) RestoreFile(*RestoreFileRequest, SecureStorage_RestoreFileServer) error {
	return status.Errorf(codes.Unimplemented, "method RestoreFile not implemented")
}
func (UnimplementedSecureStorageServer) StoreFile(SecureStorage_StoreFileServer) error {
	return status.Errorf(codes.Unimplemented, "method StoreFile not implemented")
}
func (UnimplementedSecureStorageServer) mustEmbedUnimplementedSecureStorageServer() {}

// UnsafeSecureStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecureStorageServer will
// result in compilation errors.
type UnsafeSecureStorageServer interface {
	mustEmbedUnimplementedSecureStorageServer()
}

func RegisterSecureStorageServer(s grpc.ServiceRegistrar, srv SecureStorageServer) {
	s.RegisterService(&SecureStorage_ServiceDesc, srv)
}

func _SecureStorage_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureStorageServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SecureStorage/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureStorageServer).Register(ctx, req.(*UserRegRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecureStorage_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureStorageServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SecureStorage/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureStorageServer).Login(ctx, req.(*UserRegRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecureStorage_RestoreFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RestoreFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SecureStorageServer).RestoreFile(m, &secureStorageRestoreFileServer{stream})
}

type SecureStorage_RestoreFileServer interface {
	Send(*RestoreFileResponse) error
	grpc.ServerStream
}

type secureStorageRestoreFileServer struct {
	grpc.ServerStream
}

func (x *secureStorageRestoreFileServer) Send(m *RestoreFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SecureStorage_StoreFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SecureStorageServer).StoreFile(&secureStorageStoreFileServer{stream})
}

type SecureStorage_StoreFileServer interface {
	SendAndClose(*StoreFileResponse) error
	Recv() (*StoreFileRequest, error)
	grpc.ServerStream
}

type secureStorageStoreFileServer struct {
	grpc.ServerStream
}

func (x *secureStorageStoreFileServer) SendAndClose(m *StoreFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *secureStorageStoreFileServer) Recv() (*StoreFileRequest, error) {
	m := new(StoreFileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SecureStorage_ServiceDesc is the grpc.ServiceDesc for SecureStorage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecureStorage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SecureStorage",
	HandlerType: (*SecureStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _SecureStorage_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _SecureStorage_Login_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RestoreFile",
			Handler:       _SecureStorage_RestoreFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StoreFile",
			Handler:       _SecureStorage_StoreFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/handler.proto",
}
